{% set name = "executor" %}
{% set version = "22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 596e8cf766eda61964609766abd14d02b9a6538c0159eb3980329c05d56e44bc

build:
  number: 0
  noarch: python
  entry_points:
    - executor = executor.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - coloredlogs >=3.5
    - fasteners >=0.14.1
    - humanfriendly >=3.5
    - property-manager >=2.3
    - python
    - six >=1.9.0

test:
  imports:
    - executor
    - executor.ssh
  commands:
    - executor --help

about:
  home: https://executor.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Programmer friendly subprocess wrapper
  doc_url: https://executor.readthedocs.io/en/latest/
  dev_url: https://github.com/xolox/python-executor

extra:
  recipe-maintainers:
    - rpetit3
