travis:
  secure:
    BINSTAR_TOKEN: O/tl55k7VbSZypT1/K2RFfeCJId+csF1iIg3wrsyID/IpEfNsSKOKh96ehyee5RDvyNwn34Y1xNdCa2/i5Uom/Bs9GZ9sADrxx+Nni/krrjcbvIG2uibaYSjRgIU2rNSBcRWr40ibMv29HkOBQLv1VntRp5cNqcqZ45LqQpWtOdS7Lw7CznwvE7tW6KeVyGzhAqybTS8LNODn81oBZfA/Jpoc+PuSVfMZr5CevJIDhkZquKVL4R5RGcRzPMkdJCNEdD75sfd3vYGXsKZbiNcgoUQ2ykG6MmeN+Ijz8LnpAWVSn2P2VPmgCAGwGDpcv0BxyfxeDRAhS9fwS8KTv54FAm35pVB1dY21X/OAypZ7KK5IHfqvzTm3lpJEJWK+yrV1tO5vCWGW+419Cpap6Or8T6XLWVNFUuU1SK/U4rp1i5PHu+Sbk6DapxAQXvBLcYoRJR5vHVEpOO92+pfQEW5u6A5BZwWRmGoS9RFyrZlx1VlZze2PrtZToVDlTSu5rdr8JRlR5SKCD9UJolk4IczPZ+cggS+MtdE2GcigMha8jJaWQqS0TS8+RpFs8NDHb9TPHixz4dog55fbk5g8t0KozJpjfwxauqLmLv5dUXaBW0ckdKUCdf5HZrWqTH830rIqef914VNMt8ZYDoRW7Ld5skpA5ewLMVyNtD4d/v6Vq0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
